version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo S3 Copy Started
      - aws s3 sync ./build/ s3://calendar
      - echo S3 Copy Completed
      - echo Build completed on `date`
      - echo Done




